name: ENAFUL-BOT-RUNNER

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *' # প্রতি ৬ ঘণ্টা অন্তর অটো রান হবে

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ENAFUL Bot
        env:
          FB_COOKIE: ${{ secrets.FB_COOKIE }}
          ADMIN_ID: "100001890117053"
        run: python main.py # আপনার মেইন ফাইলের নাম এখানে দিন
